env: "prod"
storage:
  storage_path: 
  dsn:
    user: "root"
    password: "root"
    protocol: "tcp"
    host: "127.0.0.1"
    port: "3306"
    name_db: "agency"
  conn_max_lifetime: 0
  max_idle_conns: 50
  max_open_conns: 50
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 30s
  user: "admin"
  password: "admin"